/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dfe3e7",
        "on-background": "#dfe3e7",
        "on-surface": "#dfe3e7",
        "on-error": "#690005",
        "secondary-container": "#00c7a5",
        "surface-tint": "#b9c7e4",
        "on-tertiary-fixed-variant": "#374767",
        "surface-container-lowest": "#0a0f12",
        "tertiary-fixed": "#d8e2ff",
        "background": "#0f1417",
        "on-secondary-fixed": "#002019",
        "tertiary": "#b6c6ed",
        "surface-variant": "#313539",
        "surface-container-highest": "#313539",
        "secondary": "#41e4c0",
        "outline": "#8f9097",
        "on-surface-variant": "#c5c6cd",
        "on-tertiary-container": "#7282a5",
        "primary-container": "#0a192f",
        "surface-container": "#1b2023",
        "tertiary-fixed-dim": "#b6c6ed",
        "tertiary-container": "#061836",
        "secondary-fixed-dim": "#38debb",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#74829d",
        "on-primary-fixed": "#0d1c32",
        "surface-container-low": "#171c1f",
        "on-primary-fixed-variant": "#39475f",
        "error-container": "#93000a",
        "on-primary": "#233148",
        "outline-variant": "#44474d",
        "on-secondary-fixed-variant": "#005142",
        "surface": "#0f1417",
        "on-secondary": "#00382d",
        "on-tertiary-fixed": "#091b39",
        "inverse-on-surface": "#2c3134",
        "surface-dim": "#0f1417",
        "error": "#ffb4ab",
        "on-secondary-container": "#004d3f",
        "primary-fixed": "#d6e3ff",
        "inverse-primary": "#515f78",
        "surface-container-high": "#262b2e",
        "primary": "#b9c7e4",
        "on-tertiary": "#20304f",
        "surface-bright": "#353a3d",
        "secondary-fixed": "#5ffbd6",
        "primary-fixed-dim": "#b9c7e4",
        "aqua-glow": "#64FFDA",
        "ocean-deep": "#0A192F",
        "ocean-surface": "#112240"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
